### ISSUE TITLE
[html] 花式Hello World

### ISSUE THREAD

**Issue by wwqin** [NJUPT-SACC/One-Plus-One-Question#1]
第1天 程序员每次第一次输出都是Hello World，前端工程师当然也不能例外，请用你所能想到的方法花式输出一个Hello World

**Comment by HKFPouu** [comment]
```html
  <div class="container">
    <div class="content"></div>
  </div>
  <div class="follow"></div>
```

```css
    * {
      margin: 0;
      padding: 0;
    }

    body {
      cursor: none;
      overflow: hidden;
      width: 100vw;
      height: 100vh;
    }

    .container {
      height: 100vh;
      background: #8ca4af;
    }

    .container,
    .content {
      display: flex;
      justify-content: center;
      align-items: center;
    }

    .content {
      background: #567c8e;
      width: 30vw;
      height: 30vh;
      color: #ffffff;
      font-size: 3.5em;
      transform: rotate(10deg);
      transition: all .5s ease-in-out;
      opacity: 0.5;
    }

    .content:hover {
      box-shadow: 9px 14px 20px 4px #2525256b;
      transform: rotate(0);
      transform: scale(1.1);
      opacity: 1;
    }

    .follow {
      width: 50px;
      height: 50px;
      border-radius: 50%;
      background: linear-gradient(45deg,#8ca4af,#ffffff);
          box-shadow: 2px 2px 20px 2px #ffffff;
      position: absolute;
    }
```

```js
  let i = 0,
    content = 'Hello world';

  function show() {
    str = content.substr(0, i);
    document.querySelector('.content').innerHTML = str + '';
    i++;
    setTimeout("show()", 400);
  }
  show()
  let follow = document.querySelector('.follow')
  document.onmousemove = function (event) {
    let evt = event || window.event,
      x = evt.clientX,
      y = evt.clientY;
    follow.style.left = x + "px";
    follow.style.top = y + "px";
  }
```
